Run PR checks against really newest merge commit
"github.event.pull_request.merge_commit_sha" is not what it states. What a mess.
"github.ref is likely a default for "checkout" but isn't states clear either.
So let's set this explicitly.

Link: https://docs.github.com/en/actions/reference/workflows-and-actions/contexts
Link: https://github.com/actions/checkout
Signed-off-by: Konstantin Khlebnikov <khlebnikov@nebius.com>

diff --git a/.github/workflows/pr-up-to-date.yaml b/.github/workflows/pr-up-to-date.yaml
--- a/.github/workflows/pr-up-to-date.yaml
+++ b/.github/workflows/pr-up-to-date.yaml
@@ -4,6 +4,9 @@ on:
   pull_request: {}
 
 env:
+  # https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-to-a-pr-using-the-built-in-token
+  GIT_COMMITTER_NAME: "github-actions[bot]"
+  GIT_COMMITTER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
   PR_BASE: ${{ github.event.pull_request.base.ref }}
   PR_HEAD: ${{ github.event.pull_request.head.sha }}
 
@@ -22,9 +25,17 @@ jobs:
 
       - name: Has latest commits
         run: |
+          set -eux -o pipefail
           if git merge-base --is-ancestor "origin/${PR_BASE}" HEAD; then
             echo "OK: PR branch is on top of the ${PR_BASE}."
+            exit 0
+          fi
+          COUNT=$(git rev-list --count "origin/${PR_BASE}" --not HEAD)
+          git checkout -d "origin/${PR_BASE}"
+          if git cherry-pick "${PR_HEAD}" --not "origin/${PR_BASE}"; then
+            echo "::warning::PR branch is ${COUNT} commit(s) behind ${PR_BASE} and can be rebased without conflicts."
+            exit 2
           else
-            echo "::error::PR branch is $(git rev-list --count "origin/${PR_BASE}" --not HEAD) commit(s) behind ${PR_BASE} and PROBABLY needs to be rebased."
+            echo "::error::PR branch is ${COUNT} commit(s) behind ${PR_BASE} and need to be rebased."
             exit 1
           fi
